<?php
//
// File generated by Dolibarr installer 20.0.4 on 28 Fév. 2025
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
if (isset($_ENV['VERCEL']) || isset($_SERVER['VERCEL']) || isset($_SERVER['HTTP_X_VERCEL_ID'])) {
	$dolibarr_main_url_root = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? "https" : "http") . "://" . ($_SERVER['HTTP_HOST'] ?? 'localhost');
	$dolibarr_main_document_root = str_replace('\\', '/', dirname(__DIR__));
	$dolibarr_main_url_root_alt = '/custom';
	$dolibarr_main_document_root_alt = $dolibarr_main_document_root . '/custom';
	$dolibarr_main_data_root = '/tmp';
} elseif (stristr(PHP_OS, 'WIN') || (isset($_SERVER['HTTP_HOST']) && strpos($_SERVER['HTTP_HOST'], 'localhost') !== false)) {
	$dolibarr_main_url_root = 'http://localhost:8000';
	$dolibarr_main_document_root = str_replace('\\', '/', dirname(__DIR__));
	$dolibarr_main_url_root_alt = '/custom';
	$dolibarr_main_document_root_alt = $dolibarr_main_document_root . '/custom';
	$dolibarr_main_data_root = $dolibarr_main_document_root . '/documents';
} else {
	$dolibarr_main_url_root='https://gestion.akablishop.ma';
	$dolibarr_main_document_root="/home/u134104531/domains/akablishop.ma/public_html/gestion_app_akabli";
	$dolibarr_main_url_root_alt='/custom';
	$dolibarr_main_document_root_alt="/home/u134104531/domains/akablishop.ma/public_html/gestion_app_akabli/custom";
	$dolibarr_main_data_root="/home/u134104531/domains/akablishop.ma/public_html/gestion_app_akabli/documents";
}
$dolibarr_main_db_host='localhost';
$dolibarr_main_db_port='0';
$dolibarr_main_db_name='u134104531_akabligest';
$dolibarr_main_db_prefix='llx_';
$dolibarr_main_db_user='u134104531_akabligest';
$dolibarr_main_db_pass='ElafConsult@123456';
$dolibarr_main_db_type='mysqli';
$dolibarr_main_db_character_set='utf8';
$dolibarr_main_db_collation='utf8_unicode_ci';
// Authentication settings
$dolibarr_main_authentication='dolibarr';

//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod='0';
$dolibarr_main_force_https='0';
$dolibarr_main_restrict_os_commands='mariadb-dump, mariadb, mysqldump, mysql, pg_dump, pg_restore, clamdscan, clamdscan.exe';
$dolibarr_nocsrfcheck='0';
$dolibarr_main_instance_unique_id='7121fc42feb10b11bc1c726162f1e100';
$dolibarr_mailing_limit_sendbyweb='0';
$dolibarr_mailing_limit_sendbycli='0';

//$dolibarr_lib_FPDF_PATH="";
//$dolibarr_lib_TCPDF_PATH="";
//$dolibarr_lib_FPDI_PATH="";
//$dolibarr_lib_TCPDI_PATH="";
//$dolibarr_lib_GEOIP_PATH="";
//$dolibarr_lib_NUSOAP_PATH="";
//$dolibarr_lib_ODTPHP_PATH="";
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP="";
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';

//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib='standard';
